import esbuild from 'esbuild';
import process from 'node:process';
import { builtinModules } from 'node:module';

const banner = `/*
Selection Translate for Obsidian — bundled build artifact.
Do not edit this file directly; edit the sources under src/ and run \`npm run build\`.
Source: https://github.com/sonthicse/osidian-selection-translate
*/
`;

const production = process.argv[2] === 'production';

/*
 * Everything Obsidian already ships inside its renderer must stay external, or
 * the bundle would carry a second, conflicting copy of CodeMirror. The explicit
 * package names cover today's Obsidian; the trailing wildcards keep the build
 * correct when Obsidian adds another @codemirror/* or @lezer/* module.
 */
const external = [
  'obsidian',
  'electron',
  '@codemirror/autocomplete',
  '@codemirror/collab',
  '@codemirror/commands',
  '@codemirror/language',
  '@codemirror/lint',
  '@codemirror/search',
  '@codemirror/state',
  '@codemirror/view',
  '@codemirror/*',
  '@lezer/common',
  '@lezer/highlight',
  '@lezer/lr',
  '@lezer/*',
  ...builtinModules,
  ...builtinModules.map((name) => `node:${name}`),
];

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external,
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: production ? false : 'inline',
  treeShaking: true,
  minify: production,
  outfile: 'main.js',
  platform: 'browser',
  define: {
    'process.env.NODE_ENV': production ? '"production"' : '"development"',
  },
});

if (production) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
